version: 2.1

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout
      - run: make deps
      - run: make lint
      - run: make test
      - docker/check
      - docker/build:
          image: wrx98794/hello-world-printer
          tag: latest
      - docker/push:
          image: wrx98794/hello-world-printer
          tag: latest

workflows:
  basic:
    jobs:
      - build-and-test